// Small, hand-authored preview fixtures. Live mode gets content only from the MAL API.
export const demo = [
  [
    1,
    "Cowboy Bebop",
    "4/19644.jpg",
    ["Action", "Sci-Fi", "Drama"],
    26,
    1998,
    "tv",
    "Spike Spiegel and Jet Black travel the solar system aboard the Bebop, chasing bounties to make ends meet. Their growing crew brings pasts that are harder to escape than any criminal.",
    "Sunrise",
    ["18, 111, 139", "142, 39, 64"],
  ],
  [
    9253,
    "Steins;Gate",
    "1935/127974.jpg",
    ["Drama", "Sci-Fi", "Suspense"],
    24,
    2011,
    "tv",
    "A self-proclaimed scientist and his friends stumble onto a way to send messages into the past. Each experiment brings unexpected consequences.",
    "White Fox",
    ["29, 98, 127", "120, 66, 101"],
  ],
  [
    47917,
    "Bocchi the Rock!",
    "1448/127956.jpg",
    ["Comedy", "Music"],
    12,
    2022,
    "tv",
    "A shy guitarist joins a small band and takes her first uncertain steps toward playing on stage and finding friends through music.",
    "CloverWorks",
    ["79, 83, 155", "174, 58, 111"],
  ],
  [
    1535,
    "Death Note",
    "1079/138100.jpg",
    ["Suspense", "Supernatural"],
    37,
    2006,
    "tv",
    "A student discovers a notebook with a deadly power. His secret campaign draws the attention of a brilliant detective, beginning a battle of wits.",
    "Madhouse",
    ["54, 87, 109", "131, 37, 50"],
  ],
  [
    4224,
    "Toradora!",
    "5/22125l.jpg",
    ["Romance", "Drama"],
    25,
    2008,
    "tv",
    "Two classmates with intimidating reputations make an unlikely pact to help each other with their crushes. Their friendship changes what they thought they wanted.",
    "J.C.Staff",
    ["44, 111, 129", "161, 59, 65"],
  ],
  [
    199,
    "Spirited Away",
    "6/79597.jpg",
    ["Adventure", "Fantasy"],
    1,
    2001,
    "movie",
    "After her family enters a mysterious spirit world, Chihiro must find her courage and a way home while working in a bustling bathhouse.",
    "Studio Ghibli",
    ["31, 113, 106", "146, 50, 84"],
  ],
  [
    5114,
    "Fullmetal Alchemist: Brotherhood",
    "1223/96541.jpg",
    ["Action", "Adventure", "Fantasy"],
    64,
    2009,
    "tv",
    "Two brothers search for a way to restore their bodies after a forbidden alchemy experiment, uncovering a conspiracy that reaches across their country.",
    "Bones",
    ["34, 93, 141", "151, 49, 48"],
  ],
].map(
  ([
    id,
    title,
    cover,
    genres,
    episodes,
    year,
    format,
    synopsis,
    studio,
    palette,
  ]) => ({
    id,
    title,
    originalTitle: title,
    image: "https://cdn.myanimelist.net/images/anime/" + cover,
    genres,
    episodes,
    year,
    format,
    synopsis,
    studios: [studio],
    status: "finished_airing",
    duration: format === "movie" ? 125 : 24,
    nsfw: "white",
    prequels: [],
    recommendations: [],
    palette,
    demo: true,
  }),
);
